repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.3
  hooks:
  - id: isort
    name: isort
    entry: poetry run isort
    language: python
    types: [python]
    always_run: true

- repo: https://github.com/hhatto/autopep8
  rev: v2.0.4
  hooks:
  - id: autopep8
    entry: poetry run autopep8
    args: ["--max-line-length=150", "--in-place"]
    language: python
    types: [python]
    always_run: true
